version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "Autosaloon_db"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    container_name: autosaloon_postgres_db
  app:
    build: .
    volumes:
      - .:/autosaloon_app
    ports:
      - 8000:8000
    image: app:autosaloon_app
    env_file: .env
    container_name: autosaloon_app_container
    command: ["python",  "manage.py",  "runserver",  "0.0.0.0:8000"]
    depends_on:
      - db
  redis:
    image: redis:alpine
    container_name: redis


