version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "Autosaloon_db"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    container_name: autosaloon_postgres_db
  app:
    build: .
    volumes:
      - .:/autosaloon_app
    ports:
      - 8000:8000
    image: app:autosaloon_app
    env_file: .env
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    container_name: autosaloon_app_container
    command: ["python",  "manage.py",  "runserver",  "0.0.0.0:8000"]
    depends_on:
      - db
  redis:
    image: redis:alpine
    container_name: redis
  celery:
    restart: always
    build:
      context: .
    command: celery -A autosaloon worker -l INFO
    volumes:
      - .:/autosaloon_app
    container_name: celery
    depends_on:
      - db
      - redis
      - app


