# Generated by Django 3.2.17 on 2023-02-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230213_1336'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cars.auto'),
        ),
    ]
