# Generated by Django 4.1.6 on 2023-02-16 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import trading.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_salooncars_car_remove_salooncars_saloon'),
        ('trading', '0002_alter_offer_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSaloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('car_characteristics', models.JSONField(default=dict, validators=[trading.validators.check_characteristics_field])),
                ('car_models_to_trade', models.JSONField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaloonCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloons_selling', to='cars.auto')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_in_saloon', to='trading.autosaloon')),
            ],
        ),
        migrations.AlterField(
            model_name='dealertosaloonhistory',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_bought_by_saloon', to='trading.autosaloon'),
        ),
        migrations.AlterField(
            model_name='saloontobuyerhistory',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_sold_by_saloon', to='trading.autosaloon'),
        ),
    ]
