# Generated by Django 3.2.17 on 2023-02-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_autosaloon_salooncars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
