# Generated by Django 3.2.18 on 2023-02-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_dealer_buyer_discounts'),
        ('trading', '0006_dealerdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerdiscount',
            name='discounted_offers',
            field=models.ManyToManyField(blank=True, related_name='car_discount', to='cars.DealerCars'),
        ),
    ]
