# Generated by Django 3.2.18 on 2023-02-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_autosaloon_salooncars'),
        ('trading', '0008_saloondiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salooncars',
            name='car',
        ),
        migrations.RemoveField(
            model_name='salooncars',
            name='saloon',
        ),
        migrations.AlterField(
            model_name='dealertosaloonhistory',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_bought_by_saloon', to='cars.autosaloon'),
        ),
        migrations.AlterField(
            model_name='saloondiscount',
            name='discounted_offers',
            field=models.ManyToManyField(blank=True, related_name='car_discount', to='cars.SaloonCars'),
        ),
        migrations.AlterField(
            model_name='saloondiscount',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='cars.autosaloon'),
        ),
        migrations.AlterField(
            model_name='saloontobuyerhistory',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_sold_by_saloon', to='cars.autosaloon'),
        ),
        migrations.DeleteModel(
            name='AutoSaloon',
        ),
        migrations.DeleteModel(
            name='SaloonCars',
        ),
    ]
