# Generated by Django 3.2.17 on 2023-02-09 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField(blank=True)),
                ('foundation_date', models.DateField()),
                ('cars_sold', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='autosaloon',
            name='car_characteristics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='autosaloon',
            name='car_models_to_trade',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='DealerCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers_selling', to='cars.auto')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_selling', to='cars.dealer')),
            ],
        ),
    ]
