# Generated by Django 3.2.17 on 2023-02-10 09:07

import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20230209_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosaloon',
            name='car_characteristics',
            field=models.JSONField(default=dict, validators=[cars.validators.check_characteristics_field]),
        ),
        migrations.AlterField(
            model_name='autosaloon',
            name='car_models_to_trade',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dealercars',
            constraint=models.UniqueConstraint(fields=('dealer', 'car'), name='Must be unique'),
        ),
    ]
