# Generated by Django 4.1.6 on 2023-02-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230213_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salooncars',
            name='car',
        ),
        migrations.RemoveField(
            model_name='salooncars',
            name='saloon',
        ),
    ]
