# Generated by Django 4.1.6 on 2023-02-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_autosaloon_salooncars_and_more'),
        ('cars', '0005_remove_salooncars_car_remove_salooncars_saloon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoSaloon',
        ),
        migrations.DeleteModel(
            name='SaloonCars',
        ),
    ]
