# Generated by Django 3.2.18 on 2023-02-20 15:25

from django.db import migrations, models
import trading.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_dealer_buyer_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='buyer_discounts',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[trading.validators.check_discount_field]),
        ),
    ]
