# Generated by Django 4.1.7 on 2023-03-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0010_auto_20230307_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosaloon',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saloon_inst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_inst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='salooncars',
            constraint=models.UniqueConstraint(fields=('saloon', 'car'), name='Must be unique record'),
        ),
    ]
